### ISSUE TITLE
KV Value Issue

### ISSUE THREAD

**Issue by apnadimp** [nk-gears/wpa-adf-blob-feed#10]
please refer to my email for additional details and screenshots .Just pasting the summary here for reference.

Changes to be made:
•	Since both the new and old code are running into issues where the KV value is being passed something must have changed with they way the value is being passed please look into it .
•	Details of the ADF deployments run with New code (RG wpatest_adfrg ,APP Name wpatest_adfapp) and the one with old code (RG m365_rg ,APP Name m365_app) ,in case you want to test or Validate
•	Folder structure is not being created correctly  with the new code ,can you please look into it and also can the file names be friendly in this format (p2g_2020-07-11-0446 or bcd_2020-07-11-0445)
•	On the Prod environment the issue is completely different ,I still need to troubleshoot but looks like some permissions issues.

**Comment by nk-gears** [comment]
Thanks for the details Aparna. Appreciate your efforts on this.
