### ISSUE TITLE
Azure Resource Naming Conventions

### ISSUE THREAD

**Issue by nk-gears** [nk-gears/wpa-adf-blob-feed#2]
Follow friendly naming convention for all the components-

**Comment by apnadimp** [comment]
@nirmal as discussed the Naming conventions should be friendly enough for the end used to identify the resources easily.

**Comment by nk-gears** [comment]
Hi Aparna, I have added an option to partition the output by date/month/year in the target. Hope this helps. I can quickly show a demo on this.
