### ISSUE TITLE
Data Grouping

### ISSUE THREAD

**Issue by nk-gears** [nk-gears/wpa-adf-blob-feed#3]
Come up with a logical way to save the data as it gets loaded from multiple ADF’s -I was thinking of grouping by date

**Comment by apnadimp** [comment]
@nirmal as discussed the files should be saved based in the date(when the file is loaded).

**Comment by nk-gears** [comment]
I have implemented a logic based on Date and Entity Name 2020/meetingInfo . Please let me know if this works
