### ISSUE TITLE
ShowParametersScript

### ISSUE THREAD

**Issue by apnadimp** [nk-gears/wpa-adf-blob-feed#8]
Parameters required In show parameters script are currently RG and AD App name but if the customer wants to deploy the script through "Deploy to Azure UI" and have already created the APP but wants to create a new RG then the parameter doesn't make sense and either ways the script just returns the Application ID and  SPN of the APP so there is no need to pass the RG parameter.

**Comment by nk-gears** [comment]
This has been implemented as requested
