### ISSUE TITLE
Existing Storage Container

### ISSUE THREAD

**Issue by apnadimp** [nk-gears/wpa-adf-blob-feed#9]
Nirmal customers want to use an existing storage account and an existing container but looks like as of now the script takes the value and uses it as a prefix and creates a new storage account every time . Can you please include this as a part of the script to validate and accept the storage acct and the container if they exists in the RG.
This issue Occurred in our prod env where I do not permissions to create new objects but have access in the existing Storage account

Deployment failed with multiple errors: 'Authorization failed for template resource 'wpicrmengagementsblob3al7ndedcrygy' of type 'Microsoft.Storage/storageAccounts'. The client 'apnadimp@microsoft.com' with object id 'f3d74a9a-b357-4023-964a-3c907b002712' does not have permission to perform action

![image](https://user-images.githubusercontent.com/66338670/86294639-f5328600-bbc2-11ea-9bc8-d772f0c5ff6a.png)

Like in the below screenshot I want to copy the Odata feed data into the existing Account/container since the historical data exists there .
![image](https://user-images.githubusercontent.com/66338670/86293324-645aab00-bbc0-11ea-98a1-e8dd8ff7401b.png)

**Comment by nk-gears** [comment]
Noted Aparna. I will add the support for the existing container.

I will have one Parameter for both Container & Path.

e.g : Enter the Blob Path Inlcuding ContainerName : <containerName>/path_to_folder/

**Comment by nk-gears** [comment]
Implemented logic for existing storage account
